# Generated by Django 5.0.6 on 2024-07-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
