# Generated by Django 5.0.6 on 2024-07-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='userModel',
            new_name='usermodel',
        ),
    ]
