# Generated by Django 5.0.6 on 2024-07-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_usermodel_customuser_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usermodel',
            field=models.CharField(choices=[(1, 'Manager'), (2, 'Employee')], max_length=200, null=True),
        ),
    ]
