# Generated by Django 5.0.6 on 2024-07-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_customuser_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usermodel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'manager'), (2, 'employee')], null=True),
        ),
    ]
