# Generated by Django 5.0.6 on 2024-07-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customuser_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='usermodel',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
